# Generated by Django 5.1.4 on 2024-12-24 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='account',
            new_name='seller',
        ),
    ]
