# Generated by Django 5.1.4 on 2024-12-24 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderdetail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='created_at',
        ),
    ]
