# Generated by Django 5.1.4 on 2024-12-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile_name', models.CharField(max_length=255)),
                ('authentication_code', models.IntegerField(blank=True, null=True)),
                ('code_expired', models.DateTimeField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('CUSTOMER', 'Customer'), ('SELLER', 'Seller'), ('ADMIN', 'Admin')], max_length=20)),
                ('profile_photo', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
            ],
        ),
    ]
