# Generated by Django 5.1.4 on 2024-12-24 12:12

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_photo',
            field=models.TextField(blank=True, help_text='Base64 encoded image', null=True, validators=[account.models.validate_base64]),
        ),
    ]
