# Generated by Django 5.1.4 on 2024-12-24 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('REVIEW', 'New Review'), ('ORDER', 'New Order'), ('REPLY', 'New Reply'), ('STATUS', 'Order Status Update')], max_length=50)),
                ('content', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='account.account')),
            ],
        ),
    ]
