# Generated by Django 5.1.4 on 2024-12-24 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notification', '0002_initial'),
        ('reply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reply.reply'),
        ),
    ]
